#!/bin/bash -i
set -e

# Functions -------------------------------------------------------------------
usage() {
cat << EOF

usage: ./install [-h] [-a ACTION]

HyperNet installation file

optional arguments:
-a | --action    (Required)      Action to take: install/uninstall
-h | --help                      Brings up this menu

EOF
}

# Parse input arguments -------------------------------------------------------
while [[ $# -gt 0 ]]; do
    key="$1"

    case $key in
        -a|--action)
            action="${2}"      # 'install/uninstall'
            shift # past argument
            shift # past value
            ;;
        -h|--help)
            usage
            exit
            ;;
        *)
            echo -e "\nWARNING! Unknown option '${1}'"
            usage
            exit 1
            ;;
    esac
done

# Check input arguments -------------------------------------------------------
case "$action" in
    install|uninstall)
        ;;
    *)
        echo -e "\nWARNING! Unknown action '${action}'"
        usage
        exit 1
        ;;
esac

# Take action -----------------------------------------------------------------
# Remove the old installation version if present
if [[ -d "./dist" ]]; then
    # Remove package
    pip3 uninstall dist/*.whl
    rm -rf dist build prode.egg-info
fi

if [ $action == "install" ]; then

    # Add "requirements" file if not present
    if [[ ! -f "./requirements.txt" ]]; then
        pipreqs --force ./
    fi
    # Install package
    python3 setup.py bdist_wheel
    pip3 install dist/*.whl

fi
