#!/usr/bin/python3
# -*- coding: utf-8 -*-
import re
import os
import sys
sys.path.append(os.path.normpath(os.environ['WORKSPACE_PATH'] + '/CFD/HyperNet/hypernet/'))
from hypernet.apps.fitRates.fitRates import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
